### ISSUE TITLE
Warning generated with Espresso 3.3.1

### ISSUE THREAD

**Issue by jingjieyeo** [tbereau/peptideB#1]
Hi Tristan,
When I attempted to run peptideB in Espresso 3.3.1, I received the following warning:
WARNING: "inter ljforcecap" is deprecated and will be removed in some further version. Use "inter forcecap" instead.

Would it be possible to update this to enhance compatibility especially since Espresso 3.4 has been released?

**Comment by tbereau** [comment]
Should work now.

Cheers,
Tristan
