### ISSUE TITLE
Defining individual masses

### ISSUE THREAD

**Issue by jingjieyeo** [tbereau/peptideB#2]
Hi Tristan,

I compiled the latest version of Espresso to run with peptideB. I noticed that the myconfig.h needed to have the `#define MASS` option in order to set individual masses, which in your current file is commented out by default.

**Comment by tbereau** [comment]
Yes, that's true. Is the commented-out feature creating problems for running the code by default? Or did further problems show up?

**Comment by jingjieyeo** [comment]
Yes in fact peptidebuilder cannot be ran at all since it cannot set the mass of the beads. If I compiled Espresso with `#define MASS` un-commented, it runs perfectly fine.

**Comment by tbereau** [comment]
Good point, I hadn't thought of that. I'll fix this soon. Thanks for the
report!

Tristan
jingjieyeo notifications@github.com schrieb am Mo. 17. Okt. 2016 um 18:50:
