### ISSUE TITLE
Cannot use peptideB

### ISSUE THREAD

**Issue by tienp** [tbereau/peptideB#4]
Hi Tristan,

I followed the steps in the Wiki Installation, and tested the peptide.tcl file in examples folder:

peptidebuilder.tcl peptide.tcl
:: >
:: >                 ***********************
:: >                *                                 *
:: >                *        peptideB          *
:: >                *     Tristan Bereau     *
:: >                *         (2008)             *
:: >                *                                *
:: >                 ***********************
:: >
invalid command name "calc_lj_shift"
    while executing
"calc_lj_shift $sigma $ljhp_cut"
    ("foreach" body line 17)
    invoked from within
"foreach partner $3letter_list {
                        if {$partner != "GLY"} {
                                # The following condition will never be true because of the if statement two levels ab..."
    ("foreach" body line 28)
    invoked from within
"foreach name $3letter_list {
        # No interaction with GLY
        if {$name != "GLY"} {
            # The next line is there only in case we decide to turn on the nb
..."
    (in namespace eval "::peptideb" script line 113)
    invoked from within
"namespace eval peptideb {
    variable bonded_parms    ""
    variable angle_parms     ""
    variable dihedral_parms  ""
    variable nb_interactions..."
    (file "/homes/minhtien/Apps/peptideB/src/chain_interactions.tcl" line 17)
    invoked from within
"source [file join [file dirname [info script]] chain_interactions.tcl]"
    (file "/homes/minhtien/Apps/peptideB/src/chain_parameters.tcl" line 179)
    invoked from within
"source /homes/minhtien/Apps/peptideB/src/chain_parameters.tcl"
    ("package ifneeded peptideb 1.0.0" script)
    invoked from within
"package require peptideb"
    invoked from within
"::mmsg::send $this "loaded version [package require peptideb] of peptideb.""
    (file "/homes/minhtien/Apps/peptideB/peptidebuilder.tcl" line 33)
 
or with Espresso 3.3.1 on:

:: >  
:: >                 ***********************  
:: >                *                                 * 
:: >                *        peptideB          * 
:: >                *     Tristan Bereau     * 
:: >                *         (2008)             * 
:: >                *                                * 
:: >                 ***********************  
:: >  
:: >  loaded version 1.0.0 of peptideb.
:: >  loaded version 1.0.0 of peptideb::input.
:: >  loaded version 1.0.0 of peptideb::espresso.
:: >  loaded version 1.0.0 of peptideb::output.
:: >  loaded version 1.0.0 of peptideb::utils.
:: >  loaded version 1.0.0 of mmsg.
:: >  
::peptideb::utils >  Setting the random seed to clock in seconds: 460554950 
:: >  Espresso integration is turned on.
:: >  Langevin thermostat has been turned on.
::peptideb::input >  Building peptide from file 'peptide.tcl'...
::peptideb::input >  Configuration was parsed successfully.
:: >  Chemical resolution was turned on.
::peptideb::espresso >  Feeding peptide chain into ESPResSo...
::peptideb::espresso >  The box size was set to: 40.0 40.0 40.0
::peptideb::espresso > Error:  could not set interaction: 0 2 lj-angle 6.0 4.11 8. 1 -1 1 -2 2 
excessive parameter/unknown interaction type "lj-angle" in parsing non bonded interaction

I also tried other example files and it reported same errors. It would be great if you can have a look at this case. I am really interested in your intermediate level of resolution CG model.

Thank you in advance,

Tien Phan

**Comment by tbereau** [comment]
Hi Tien,

The `lj-angle` interaction is not compiled by ESPResSo by default. You need to set the `config.hpp` file such that it activates that feature, and then recompile the code. Have a look at the README file, it describes this.

Best,
Tristan

**Comment by tienp** [comment]
Thank you for your reply. After reinstalling espresso with the myconfig.hpp mentioned in the README file, now peptideB works with espresso on. However, I still cannot use  `peptidebuilder.tcl peptide.tcl`, each time it reports errors as above:
```
:: >  
:: >                 ***********************  
:: >                *                       * 
:: >                *        peptideB       * 
:: >                *     Tristan Bereau    * 
:: >                *         (2008)        * 
:: >                *                       * 
:: >                 ***********************  
:: > 
invalid command name "calc_lj_shift"
    while executing
"calc_lj_shift $sigma $ljhp_cut"
    ("foreach" body line 17)
    invoked from within
"foreach partner $3letter_list {
			if {$partner != "GLY"} {
				# The following condition will never be true because of the if statement two levels ab..."
    ("foreach" body line 28)
    invoked from within
"foreach name $3letter_list {
	# No interaction with GLY
	if {$name != "GLY"} {
	    # The next line is there only in case we decide to turn on the nb
..."
    (in namespace eval "::peptideb" script line 113)
    invoked from within
"namespace eval peptideb {
    variable bonded_parms    ""
    variable angle_parms     ""
    variable dihedral_parms  ""
    variable nb_interactions..."
    (file "/home/tien/peptideB/src/chain_interactions.tcl" line 17)
    invoked from within
"source [file join [file dirname [info script]] chain_interactions.tcl]"
    (file "/home/tien/peptideB/src/chain_parameters.tcl" line 179)
    invoked from within
"source /home/tien/peptideB/src/chain_parameters.tcl"
    ("package ifneeded peptideb 1.0.0" script)
    invoked from within
"package require peptideb"
    invoked from within
"::mmsg::send $this "loaded version [package require peptideb] of peptideb.""
    (file "../peptidebuilder.tcl" line 33)
```
I think there are some problems working with tcl files on my Ubuntu 16.04. Anyway, at least it works with   espresso.

**Comment by tbereau** [comment]
`peptidebuilder.tcl` requires `ESPResSo` if you want to run dynamics. Without it, you can only use it for very limited purposes (e.g., system setup or analysis).

**Comment by tienp** [comment]
I think `peptidebuilder.tcl` is very useful for building the CG system to run on other simulation softwares, e.g.  `LAMMPS` or `DL_POLY`. BTW,  I also like your `vmd_plg.tcl`.

Thanks for your help and very useful `peptideB`.
