### ISSUE TITLE
Cannot run REMD with peptideB

### ISSUE THREAD

**Issue by TienMPhan** [tbereau/peptideB#5]
Hi Tristan,

I've been testing the examples with `peptideB` for some time. Everything works fine except for the remd. I use the command in the Wiki Page to run replica exchange as the fllowing
`Espresso peptidebuilder.tcl polyala.tcl -replica -connect`.
It returns
```
:: >  loaded version 1.0.0 of peptideb.
:: >  loaded version 1.0.0 of peptideb::input.
:: >  loaded version 1.0.0 of peptideb::espresso.
:: >  loaded version 1.0.0 of peptideb::output.
:: >  loaded version 1.0.0 of peptideb::utils.
:: >  loaded version 1.0.0 of mmsg.
:: >  
:: >  Replica exchange algorithm has been turned on.
```
and stops there all the time.
I followed closely the guides in the `Installation Page`, so I don't know what's wrong in the procedure. I tried other examples but it just stopped there.
I know it has been ten years since you worked on this project, so it would be great if you still remember something and give me some tips to get it run.

Thank you in advance,

Martin

**Comment by tbereau** [comment]
Hi Martin,

So you need one command per replica you're running. So say you run 4 replicas. You'd have one command from the master with

`Espresso peptidebuilder.tcl polyala.tcl -replica`

and in other terminals or on other computers (that are connected) 3 times:

`Espresso peptidebuilder.tcl polyala.tcl -replica -connect`

the log of the master should be listening for slave instances to connect. Does that help?

**Comment by TienMPhan** [comment]
Oh, I see. The command from the master (or server) on the first terminal listens to the slaves (or clients) on the others terminals in order to connect and run. I didn't imagine that scenario when I first read the `Quick Start`, but it works now. Thank you for your help, it saves my day!

Best,

Martin
